apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-mainframe.fullname" . }}-secrets
  labels:
    {{- include "open-mainframe.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_url: {{ include "open-mainframe.databaseUrl" . | quote }}
